var Promise = require('bluebird');
var writeFile = Promise.promisify(require('fs').writeFile);

var domain = require('./domain/production.js');

var diff = require('./domain/production/cdTemplateController.js');

domain.getBuilds().then(builds => {
  return Promise.all(builds.map(b => {
    if (b.output.cdtemplate) {
      return diff.getCurrentDiff(b).then(d => {
        b.cdtemplate = d;
        if (!d) {
          // remove inconsistencies generated by dodgey diffs
          b.output.cdtemplate = null;
        }
        return b;
      });
    } else {
      return Promise.resolve(b);
    }
  }));
}).then(builds => {
  return writeFile('builds.json', JSON.stringify(builds, null, 4));
}).then(()=>{
  console.log('test data populated.');
});
